### ISSUE TITLE
why is there no option to give a body in the send function of StompSockWebSocket?

### ISSUE THREAD

**Issue by mradamhoward** [oril-software/ng-stomp-sock#4]
I tried sending messages but you have no function for the send with a body. I can't send any data to the rest api, just a blank send. Am I missing something?

**Comment by alexander-panchuk-oril** [comment]
Hey @mradamhoward ,
Thanks for your question. In readme.md you can find an example of send request:

>  public send() {
>     this.activityWS.send(this._requestEndpoint, { });
>   }

Instead of "{ }" you can pass any object and it will attach the object to a sending body.

Feel free to ask if you have any additional questions 👀
