### ISSUE TITLE
send method

### ISSUE THREAD

**Issue by dacodemaniak** [oril-software/ng-stomp-sock#5]
Hi, 
First of all, really good job...
I try to implement your package in my own client, but i'm facing an issue while sending data to spring backend.

import { Injectable } from '@angular/core';
import { StompSockService, StompSockWebSocket, WsCommand } from '@oril/ng-stomp-sock';

import { environment } from '@environment/environment';

```
import { filter } from 'rxjs/operators';
import { Observable } from 'rxjs';
import { MessageInterface } from '../interfaces/message-interface';
@Injectable({
  providedIn: 'root'
})
export class WsChatService {
  private readonly endpoint: string = `${environment.socketApiURL}/topic/public`;
  private readonly requestEndpoint: string = '/app';

  private webSocket!: StompSockWebSocket;

  constructor(
    private _websocketService: StompSockService
  ) { 
  }

  public doConnect(): Promise<void> {
    return new Promise((resolve: any) => {
      this._websocketService.connected$
      .pipe(
        filter((connected) => !!connected)
      )
      .subscribe(() => {
        this.webSocket = this._websocketService.getWebSocket(this.endpoint);
        resolve();
      });
    });

  }

  public doDisconnect(): void {
    this._websocketService.unsubscribe(this.endpoint);
  }

  public onReceive(): Observable<any> {
    console.log(`Receiving some datas from backend`);
    return this.webSocket.on<any>(WsCommand.MESSAGE)
  }

  public send(endpoint: string, message?: MessageInterface): void {
    console.log(`Sending greeting message : ${JSON.stringify(message)}`);
    **this.webSocket.send(`${this.requestEndpoint}/${endpoint}`, {chatMessage: {body: message}});**
  }
}
```
I'm not sure that it's i have to do to send a message to the endpoint of the backend 👍 

```
    @MessageMapping("/chat.hello")
    @SendTo("/topic/public")
    public ChatMessage sayHello(@Payload ChatMessage[] chatMessage) {
    	ChatMessage message = new ChatMessage();
    	message.setSender(chatMessage[0].getSender());
    	message.setContent("Hi all");
    	message.setType(chatMessage[0].getType());
    	
        return message;
    }
```
Socket is fully connected but endpoint failed with a token Object that cannot be resolved by Jackson... Frame sended is 👍 

`0: "SEND\ndestination:/app/chat.hello\nchatMessage:{\"body\"\\c{\"sender\"\\c\"dacodemaniak\",\"type\"\\c\"CHAT\"}}\ncontent-length:15\n\n[object Object]\u0000"`

When i see your 'send' method, i mentionned a third parameter : body that is unused in the 'publish' method... So... how do i pass the correct headers to make Spring correctly handle the message ?

Truely

**Comment by alexander-panchuk-oril** [comment]
Hey @dacodemaniak,
Sorry for the long response.

Just released a minor update that includes sending the `body` as an optional parameter in the `send()` method.

Cheers
